module.exports = [
  { body: {
    quizzes: { name: 'Art Easy Questions', user_id: 1, difficulty: 'easy', category: 'Art' },
    questions: '[{"question":"Who painted the Mona Lisa?","corrAns":"Leonardo da Vinci","incAns1":"Pablo Picasso","incAns2":"Claude Monet","incAns3":"Vincent van Gogh"},{"question":"Who painted the Sistine Chapel?","corrAns":"Michelangelo","incAns1":"Leonardo da Vinci","incAns2":"Pablo Picasso","incAns3":"Raphael"},{"question":"Leonardo da Vinci&#039;s Mona Lisa does not have eyebrows.","corrAns":"True","incAns":"False"},{"question":"Who painted &quot;Swans Reflecting Elephants&quot;, &quot;Sleep&quot;, and &quot;The Persistence of Memory&quot;?","corrAns":"Salvador Dali","incAns1":"Jackson Pollock","incAns2":"Vincent van Gogh","incAns3":"Edgar Degas"},{"question":"Leonardo da Vinci was not the creator of the Mona Lisa.","corrAns":"False","incAns":"True"},{"question":"Who painted The Starry Night?","corrAns":"Vincent van Gogh","incAns1":"Pablo Picasso","incAns2":"Leonardo da Vinci","incAns3":"Michelangelo"},{"question":"Which Van Gogh painting depicts the view from his asylum in Saint-R&eacute;my-de-Provence in southern France?","corrAns":"The Starry Night","incAns1":"Wheatfields with Crows","incAns2":"The Sower with Setting Sun","incAns3":"The Church at Auvers"},{"question":"Which painting was not made by Vincent Van Gogh?","corrAns":"The Ninth Wave","incAns1":"Caf&eacute; Terrace at Night","incAns2":"Bedroom In Arles","incAns3":"Starry Night"},{"question":"Who painted the biblical fresco The Creation of Adam?","corrAns":"Michelangelo","incAns1":"Leonardo da Vinci","incAns2":"Caravaggio","incAns3":"Rembrandt"}]'
  },},
  { body: {
    quizzes: { name: 'Art Medium Questions', user_id: 1, difficulty: 'medium', category: 'Art' },
    questions: '[{"question":"Which time signature is commonly known as &ldquo;Cut Time?&rdquo;","corrAns":"2/2","incAns1":"4/4","incAns2":"6/8","incAns3":"3/4"},{"question":"Which artist&rsquo;s studio was known as &#039;The Factory&#039;?","corrAns":"Andy Warhol","incAns1":"Roy Lichtenstein","incAns2":"David Hockney","incAns3":"Peter Blake"},{"question":"What nationality was the surrealist painter Salvador Dali?","corrAns":"Spanish","incAns1":"Italian","incAns2":"French","incAns3":"Portuguese"},{"question":"Vincent van Gogh cut off one of his ears.","corrAns":"True","incAns":"False"},{"question":"Pablo Picasso is one of the founding fathers of &quot;Cubism.&quot;","corrAns":"True","incAns":"False"},{"question":"Which one of these paintings is not by Caspar David Friedrich?","corrAns":"The Black Sea","incAns1":"The Sea of Ice","incAns2":"Wanderer above the Sea of Fog","incAns3":"The Monk by the Sea"},{"question":"Which of these are the name of a famous marker brand?","corrAns":"Copic","incAns1":"Dopix","incAns2":"Cofix","incAns3":"Marx"},{"question":"Which artist&#039;s style was to use small different colored dots to create a picture?","corrAns":"Georges Seurat","incAns1":"Paul C&eacute;zanne","incAns2":"Vincent Van Gogh","incAns3":"Henri Rousseau"},{"question":"Who designed the Chupa Chups logo?","corrAns":"Salvador Dali","incAns1":"Pablo Picasso","incAns2":"Andy Warhol","incAns3":"Vincent van Gogh"},{"question":"Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.","corrAns":"False","incAns":"True"},{"question":"Who painted the epic mural Guernica?","corrAns":"Pablo Picasso","incAns1":"Francisco Goya","incAns2":"Leonardo da Vinci","incAns3":"Henri Matisse"}]'
  },},
  { body: {
    quizzes: { name: 'Art Hard Questions', user_id: 1, difficulty: 'hard', category: 'Art' },
    questions: '[{"question":"Painter Piet Mondrian (1872 - 1944) was a part of what movement?","corrAns":"Neoplasticism","incAns1":"Precisionism","incAns2":"Cubism","incAns3":"Impressionism"},{"question":"What French sculptor designed the Statue of Liberty? ","corrAns":"Fr&eacute;d&eacute;ric Auguste Bartholdi","incAns1":"Jean-L&eacute;on G&eacute;r&ocirc;me","incAns2":"Auguste Rodin","incAns3":"Henri Matisse"},{"question":"Albrecht D&uuml;rer&#039;s birthplace and place of death were in...","corrAns":"N&uuml;rnberg","incAns1":"Augsburg","incAns2":"Bamberg","incAns3":"Berlin"},{"question":"What year did Albrecht D&uuml;rer create the painting &quot;The Young Hare&quot;?","corrAns":"1502","incAns1":"1702","incAns2":"1402","incAns3":"1602"},{"question":"What year was the Mona Lisa finished?","corrAns":"1504","incAns1":"1487","incAns2":"1523","incAns3":"1511"},{"question":"Which of these is not an additional variation of the color purple?","corrAns":"Kobicha","incAns1":"Byzantium","incAns2":"Pomp and Power","incAns3":"Palatinate"},{"question":"How many paint and pastel versions of &quot;The Scream&quot; is Norwegian painter Edvard Munch believed to have produced?","corrAns":"4","incAns1":"1","incAns2":"3","incAns3":"2"},{"question":"The Statue of Liberty&#039;s official name is &ldquo;Liberty Enlightening the World&rdquo;.","corrAns":"True","incAns":"False"},{"question":"The painting &quot;The Starry Night&quot; by Vincent van Gogh was part of which art movement?","corrAns":"Post-Impressionism","incAns1":"Romanticism","incAns2":"Neoclassical","incAns3":"Impressionism"}]'
  },},
  { body: {
    quizzes: { name: 'Art Boolean Questions', user_id: 1, difficulty: 'hard', category: 'Art' },
    questions: '[{"question":"Leonardo da Vinci&#039;s Mona Lisa does not have eyebrows.","corrAns":"True","incAns":"False"},{"question":"Vincent van Gogh cut off one of his ears.","corrAns":"True","incAns":"False"},{"question":"Pablo Picasso is one of the founding fathers of &quot;Cubism.&quot;","corrAns":"True","incAns":"False"},{"question":"Leonardo da Vinci was not the creator of the Mona Lisa.","corrAns":"False","incAns":"True"},{"question":"Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.","corrAns":"False","incAns":"True"},{"question":"The Statue of Liberty&#039;s official name is &ldquo;Liberty Enlightening the World&rdquo;.","corrAns":"True","incAns":"False"}]'
  },},
  { body: {
    quizzes: { name: 'Art Multiple Questions', user_id: 1, difficulty: 'hard', category: 'Art' },
    questions: '[{"question":"Who painted the Mona Lisa?","corrAns":"Leonardo da Vinci","incAns1":"Pablo Picasso","incAns2":"Claude Monet","incAns3":"Vincent van Gogh"},{"question":"Painter Piet Mondrian (1872 - 1944) was a part of what movement?","corrAns":"Neoplasticism","incAns1":"Precisionism","incAns2":"Cubism","incAns3":"Impressionism"},{"question":"Which time signature is commonly known as &ldquo;Cut Time?&rdquo;","corrAns":"2/2","incAns1":"4/4","incAns2":"6/8","incAns3":"3/4"},{"question":"Who painted the Sistine Chapel?","corrAns":"Michelangelo","incAns1":"Leonardo da Vinci","incAns2":"Pablo Picasso","incAns3":"Raphael"},{"question":"What French sculptor designed the Statue of Liberty? ","corrAns":"Fr&eacute;d&eacute;ric Auguste Bartholdi","incAns1":"Jean-L&eacute;on G&eacute;r&ocirc;me","incAns2":"Auguste Rodin","incAns3":"Henri Matisse"},{"question":"Which artist&rsquo;s studio was known as &#039;The Factory&#039;?","corrAns":"Andy Warhol","incAns1":"Roy Lichtenstein","incAns2":"David Hockney","incAns3":"Peter Blake"},{"question":"What nationality was the surrealist painter Salvador Dali?","corrAns":"Spanish","incAns1":"Italian","incAns2":"French","incAns3":"Portuguese"},{"question":"Albrecht D&uuml;rer&#039;s birthplace and place of death were in...","corrAns":"N&uuml;rnberg","incAns1":"Augsburg","incAns2":"Bamberg","incAns3":"Berlin"},{"question":"What year did Albrecht D&uuml;rer create the painting &quot;The Young Hare&quot;?","corrAns":"1502","incAns1":"1702","incAns2":"1402","incAns3":"1602"},{"question":"What year was the Mona Lisa finished?","corrAns":"1504","incAns1":"1487","incAns2":"1523","incAns3":"1511"},{"question":"Who painted &quot;Swans Reflecting Elephants&quot;, &quot;Sleep&quot;, and &quot;The Persistence of Memory&quot;?","corrAns":"Salvador Dali","incAns1":"Jackson Pollock","incAns2":"Vincent van Gogh","incAns3":"Edgar Degas"},{"question":"Which one of these paintings is not by Caspar David Friedrich?","corrAns":"The Black Sea","incAns1":"The Sea of Ice","incAns2":"Wanderer above the Sea of Fog","incAns3":"The Monk by the Sea"},{"question":"Which of these are the name of a famous marker brand?","corrAns":"Copic","incAns1":"Dopix","incAns2":"Cofix","incAns3":"Marx"}]'
  },},
  { body: {
    quizzes: { name: 'GK Easy Questions', user_id: 1, difficulty: 'easy', category: 'General Knowledge' },
    questions: '[{"question":"What is the largest organ of the human body?","corrAns":"Skin","incAns1":"Heart","incAns2":"large Intestine","incAns3":"Liver"},{"question":"What geometric shape is generally used for stop signs?","corrAns":"Octagon","incAns1":"Hexagon","incAns2":"Circle","incAns3":"Triangle"},{"question":"Five dollars is worth how many nickles?","corrAns":"100","incAns1":"50","incAns2":"25","incAns3":"69"},{"question":"According to Sherlock Holmes, &quot;If you eliminate the impossible, whatever remains, however improbable, must be the...&quot;","corrAns":"Truth","incAns1":"Answer","incAns2":"Cause","incAns3":"Source"},{"question":"Which restaurant&#039;s mascot is a clown?","corrAns":"McDonald&#039;s","incAns1":"Whataburger","incAns2":"Burger King","incAns3":"Sonic"},{"question":"Scotland voted to become an independent country during the referendum from September 2014.","corrAns":"False","incAns":"True"},{"question":"The Flag of the European Union has how many stars on it?","corrAns":"12","incAns1":"10","incAns2":"14","incAns3":"16"},{"question":"How many furlongs are there in a mile?","corrAns":"Eight","incAns1":"Two","incAns2":"Four","incAns3":"Six"},{"question":"What is the closest planet to our solar system&#039;s sun?","corrAns":"Mercury","incAns1":"Mars","incAns2":"Jupiter","incAns3":"Earth"},{"question":"What airline was the owner of the plane that crashed off the coast of Nova Scotia in 1998?","corrAns":"Swiss Air","incAns1":"Air France","incAns2":"British Airways","incAns3":"TWA"}]'
  },},
  { body: {
    quizzes: { name: 'GK Medium Questions', user_id: 1, difficulty: 'medium', category: 'General Knowledge' },
    questions: '[{"question":"In the Morse code, which letter is indicated by 3 dots? ","corrAns":"S","incAns1":"O","incAns2":"A","incAns3":"C"},{"question":"The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.","corrAns":"True","incAns":"False"},{"question":"What is the German word for &quot;spoon&quot;?","corrAns":"L&ouml;ffel","incAns1":"Gabel","incAns2":"Messer","incAns3":"Essst&auml;bchen"},{"question":"Kissing someone for one minute burns about 2 calories.","corrAns":"True","incAns":"False"},{"question":"What is the Portuguese word for &quot;Brazil&quot;?","corrAns":"Brasil","incAns1":"Brazil","incAns2":"Brasilia","incAns3":"Bras&iacute;l"},{"question":"Haggis is traditionally ate on Burns Night.","corrAns":"True","incAns":"False"},{"question":"What is the currency of Poland?","corrAns":"Złoty","incAns1":"Ruble","incAns2":"Euro","incAns3":"Krone"},{"question":"The pickled gherkin was first added to hamburgers because a US health law required all fast-food to include a source of Vitamin C.","corrAns":"False","incAns":"True"},{"question":"Directly between the Washington Monument and the Reflecting Pool is a memorial to which war?","corrAns":"World War II","incAns1":"Vietnam War","incAns2":"American Civil War","incAns3":"American Revolutionary War"},{"question":"The Mexican Beer &quot;Corona&quot; is what type of beer?","corrAns":"Pale Lager","incAns1":"India Pale Ale","incAns2":"Pilfsner","incAns3":"Baltic Porter"}]'
  },},
  { body: {
    quizzes: { name: 'GK Hard Questions', user_id: 1, difficulty: 'hard', category: 'General Knowledge' },
    questions: '[{"question":"This is the correct spelling of &quot;Supercalifragilisticexpialidocious&quot;.","corrAns":"True","incAns":"False"},{"question":"Which of the following chemicals are found in eggplant seeds?","corrAns":"Nicotine","incAns1":"Mescaline","incAns2":"Cyanide","incAns3":"Psilocybin"},{"question":"Which of the following is an existing family in &quot;The Sims&quot;?","corrAns":"The Goth Family","incAns1":"The Family","incAns2":"The Simoleon Family","incAns3":"The Proud Family"},{"question":"The Swedish word &quot;Grunka&quot; means what in English?","corrAns":"Thing","incAns1":"People","incAns2":"Place","incAns3":"Pineapple"},{"question":"De Eemhof, Port Zelande and Het Heijderbos are holiday villas owned by what company?","corrAns":"Center Parcs","incAns1":"Yelloh Village","incAns2":"Keycamp","incAns3":"Villa Plus"},{"question":"According to the 2014-2015 Australian Bureau of Statistics, what percentage of Australians were born overseas?","corrAns":"28%","incAns1":"13%","incAns2":"20%","incAns3":"7%"},{"question":"Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.","corrAns":"True","incAns":"False"},{"question":"In flight systems, what does the initialism &quot;TCAS&quot; stand for?","corrAns":"Traffic Collision Avoidance System","incAns1":"Traffic Communication Alert System","incAns2":"Traffic Configuration Alignment System","incAns3":"Traffic Call-sign Abbreviation System"},{"question":"If someone said &quot;you are olid&quot;, what would they mean?","corrAns":"You smell extremely unpleasant.","incAns1":"You are out of shape/weak.","incAns2":"Your appearance is repulsive.","incAns3":"You are incomprehensible/an idiot."},{"question":"The word &quot;aprosexia&quot; means which of the following?","corrAns":"The inability to concentrate on anything","incAns1":"The inability to make decisions","incAns2":"A feverish desire to rip one&#039;s clothes off","incAns3":"The inability to stand up"}]'
  },},
  { body: {
    quizzes: { name: 'GK Boolean Questions', user_id: 1, difficulty: 'hard', category: 'General Knowledge' },
    questions: '[{"question":"Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.","corrAns":"False","incAns":"True"},{"question":"An eggplant is a vegetable.","corrAns":"False","incAns":"True"},{"question":"You can legally drink alcohol while driving in Mississippi.","corrAns":"True","incAns":"False"},{"question":"Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.","corrAns":"True","incAns":"False"},{"question":"The Lego Group was founded in 1932.","corrAns":"True","incAns":"False"},{"question":"Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.","corrAns":"True","incAns":"False"},{"question":"&quot;Santa Claus&quot; is a variety of melon.","corrAns":"True","incAns":"False"},{"question":"Scotland voted to become an independent country during the referendum from September 2014.","corrAns":"False","incAns":"True"},{"question":"Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.","corrAns":"True","incAns":"False"},{"question":"Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.","corrAns":"False","incAns":"True"}]'
  },},
  { body: {
    quizzes: { name: 'GK Multiple Questions', user_id: 1, difficulty: 'hard', category: 'General Knowledge' },
    questions: '[{"question":"What was the name of the WWF professional wrestling tag team made up of the wrestlers Ax and Smash?","corrAns":"Demolition","incAns1":"The Dream Team","incAns2":"The Bushwhackers","incAns3":"The British Bulldogs"},{"question":"What name represents the letter &quot;M&quot; in the NATO phonetic alphabet?","corrAns":"Mike","incAns1":"Matthew","incAns2":"Mark","incAns3":"Max"},{"question":"In the Morse code, which letter is indicated by 3 dots? ","corrAns":"S","incAns1":"O","incAns2":"A","incAns3":"C"},{"question":"Who is depicted on the US hundred dollar bill?","corrAns":"Benjamin Franklin","incAns1":"George Washington","incAns2":"Abraham Lincoln","incAns3":"Thomas Jefferson"},{"question":"Which of the following carbonated soft drinks were introduced first?","corrAns":"Dr. Pepper","incAns1":"Coca-Cola","incAns2":"Sprite","incAns3":"Mountain Dew"},{"question":"What direction does the Statue of Liberty face?","corrAns":"Southeast","incAns1":"Southwest","incAns2":"Northwest","incAns3":"Northeast"},{"question":"What was the soft drink Pepsi originally introduced as?","corrAns":"Brad&#039;s Drink","incAns1":"Pepsin Pop","incAns2":"Carolina Cola","incAns3":"Pepsin Syrup"},{"question":"Terry Gilliam was an animator that worked with which British comedy group?","corrAns":"Monty Python","incAns1":"The Goodies&lrm;","incAns2":"The League of Gentlemen&lrm;","incAns3":"The Penny Dreadfuls"},{"question":"The word &quot;astasia&quot; means which of the following?","corrAns":"The inability to stand up","incAns1":"The inability to make decisions","incAns2":"The inability to concentrate on anything","incAns3":"A feverish desire to rip one&#039;s clothes off"},{"question":"When was the Playstation 3 released?","corrAns":"November 11, 2006","incAns1":"January 8, 2007","incAns2":"December 25, 2007","incAns3":"July 16, 2006"}]'
  },},
  { body: {
    quizzes: { name: 'History Easy Questions', user_id: 1, difficulty: 'easy', category: 'History' },
    questions: '[{"question":"What was William Frederick Cody better known as?","corrAns":"Buffalo Bill","incAns1":"Billy the Kid","incAns2":"Wild Bill Hickok","incAns3":"Pawnee Bill"},{"question":"Who discovered Penicillin?","corrAns":"Alexander Flemming","incAns1":"Marie Curie","incAns2":"Alfred Nobel","incAns3":"Louis Pasteur"},{"question":"The idea of Socialism was articulated and advanced by whom?","corrAns":"Karl Marx","incAns1":"Vladimir Lenin","incAns2":"Joseph Stalin","incAns3":"Vladimir Putin"},{"question":"In which year did the Invasion of Kuwait by Iraq occur?","corrAns":"1990","incAns1":"1992","incAns2":"1988","incAns3":"1986"},{"question":"Who was the Prime Minister of Japan when Japan declared war on the US?","corrAns":"Hideki Tojo","incAns1":"Michinomiya Hirohito","incAns2":"Isoroku Yamamoto","incAns3":"Fumimaro Konoe"},{"question":"Who was among those killed in the 2010 Smolensk, Russia plane crash tragedy?","corrAns":"The Polish President","incAns1":"Pope John Paul II","incAns2":"Bang-Ding Ow","incAns3":"Albert Putin"},{"question":"To what political party did Abraham Lincoln belong when elected POTUS?","corrAns":"Republican","incAns1":"Democrat","incAns2":"Independent","incAns3":"Whig"},{"question":"What is the historical name of Sri Lanka?","corrAns":"Ceylon","incAns1":"Myanmar","incAns2":"Colombo","incAns3":"Badulla"},{"question":"In what year was the M1911 pistol designed?","corrAns":"1911","incAns1":"1907","incAns2":"1899","incAns3":"1917"},{"question":"In what year did the Great Northern War, between Russia and Sweden, end?","corrAns":"1721","incAns1":"1726","incAns2":"1727","incAns3":"1724"}]'
  },},
  { body: {
    quizzes: { name: 'History Medium Questions', user_id: 1, difficulty: 'medium', category: 'History' },
    questions: '[{"question":"In what year did Neil Armstrong and Buzz Aldrin land on the moon?","corrAns":"1969","incAns1":"1965","incAns2":"1966","incAns3":"1973"},{"question":"The two atomic bombs dropped on Japan by the United States in August 1945 were named &#039;Little Man&#039; and &#039;Fat Boy&#039;.","corrAns":"False","incAns":"True"},{"question":"What was the capital of South Vietnam before the Vietnam War?","corrAns":"Saigon","incAns1":"Ho Chi Minh City","incAns2":"Hanoi","incAns3":"Hue"},{"question":"Who was the first explorer to sail to North America?","corrAns":"Leif Erikson","incAns1":"Christopher Columbus","incAns2":"Amerigo Vespucci","incAns3":"Ferdinand Magellan"},{"question":"Which country had an &quot;Orange Revolution&quot; between 2004 and 2005?","corrAns":"Ukraine","incAns1":"Belarus","incAns2":"Latvia","incAns3":"Lithuania"},{"question":"In what year was the video game company Electronic Arts founded?","corrAns":"1982","incAns1":"1999","incAns2":"1981","incAns3":"2005"},{"question":"Which building was set aflame on August 24th, 1812?","corrAns":"The White House","incAns1":"Parliament Building","incAns2":"Grand National Assembly Building","incAns3":"Palace of the Nation"},{"question":"Oxford University is older than the Aztec Empire. ","corrAns":"True","incAns":"False"},{"question":"Who was the first president born in the independent United States?","corrAns":"Martin Van Buren","incAns1":"John Adams","incAns2":"George Washington","incAns3":"James Monroe "},{"question":"The Korean War ended in 1953 without any ceasefire.","corrAns":"False","incAns":"True"}]'
  },},
  { body: {
    quizzes: { name: 'History Hard Questions', user_id: 1, difficulty: 'hard', category: 'History' },
    questions: '[{"question":"With which Greek philosopher would you associate the phrase, &quot;I know that I know nothing&quot;?","corrAns":"Socrates","incAns1":"Aristotle","incAns2":"Plato","incAns3":"Pythagoras"},{"question":"When did the French Revolution begin?","corrAns":"1789","incAns1":"1823","incAns2":"1756","incAns3":"1799"},{"question":"Joseph Stalin&#039;s real name was Ioseb Bessarionis dze Dzugashvili.","corrAns":"True","incAns":"False"},{"question":"When did Canada leave the confederation to become their own nation?","corrAns":"July 1st, 1867","incAns1":"July 1st, 1763","incAns2":"July 1st, 1832","incAns3":"July 1st, 1902"},{"question":"In which year did the Tokyo Subway Sarin Attack occur?","corrAns":"1995","incAns1":"2001","incAns2":"2011","incAns3":"1991"},{"question":"When did Lithuania declare independence from the Soviet Union?","corrAns":"March 11th, 1990","incAns1":"December 25th, 1991","incAns2":"December 5th, 1991","incAns3":"April 20th, 1989"},{"question":"How many women joined the United States Armed Services during World War II?","corrAns":"350,000","incAns1":"225,000","incAns2":"100,000","incAns3":"500,000"},{"question":"Which of the following was not one of Joseph Stalin&#039;s ten blows during World War II?","corrAns":"Vistula-Oder Offensive","incAns1":"Crimean Offensive","incAns2":"Leningrad-Novgorod Offensive","incAns3":"Operation Bagration"},{"question":"Which countries participated in the Lobster War?","corrAns":"France and Brazil","incAns1":"Canada and Norway","incAns2":"Australia and New Zealand","incAns3":"United States and England"},{"question":"The son of which pope supposedly held a lecherous f&ecirc;te involving 50 courtesans in the papal palace?","corrAns":"Alexander VI","incAns1":"Innocent V","incAns2":"Urban II","incAns3":"Pius III"}]'
  },},
  { body: {
    quizzes: { name: 'History Boolean Questions', user_id: 1, difficulty: 'hard', category: 'History' },
    questions: '[{"question":"Japan was part of the Allied Powers during World War I.","corrAns":"True","incAns":"False"},{"question":"The Tiananmen Square protests of 1989 were held in Hong Kong.","corrAns":"False","incAns":"True"},{"question":"Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.","corrAns":"False","incAns":"True"},{"question":"Brezhnev was the 5th leader of the USSR.","corrAns":"True","incAns":"False"},{"question":"The United States Department of Homeland Security was formed in response to the September 11th attacks.","corrAns":"True","incAns":"False"},{"question":"The United States was a member of the League of Nations.","corrAns":"False","incAns":"True"},{"question":"Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.","corrAns":"True","incAns":"False"},{"question":"United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ","corrAns":"True","incAns":"False"},{"question":"Adolf Hitler was tried at the Nuremberg trials.","corrAns":"False","incAns":"True"},{"question":"The man that shot Alexander Hamilton was named Aaron Burr.","corrAns":"True","incAns":"False"}]'
  },},
  { body: {
    quizzes: { name: 'History Multiple Questions', user_id: 1, difficulty: 'hard', category: 'History' },
    questions: '[{"question":" What Russian automatic gas-operated assault rifle was developed in the Soviet Union in 1947, and is still popularly used today?","corrAns":"AK-47","incAns1":"RPK","incAns2":"M16","incAns3":"MG 42"},{"question":"In the War of the Pacific (1879 - 1883), Bolivia lost its access to the Pacific Ocean after being defeated by which South American country?","corrAns":"Chile","incAns1":"Peru","incAns2":"Brazil","incAns3":"Argentina"},{"question":"When did Canada leave the confederation to become their own nation?","corrAns":"July 1st, 1867","incAns1":"July 1st, 1763","incAns2":"July 1st, 1832","incAns3":"July 1st, 1902"},{"question":"During the Roman Triumvirate of 42 BCE, what region of the Roman Republic was given to Lepidus?","corrAns":"Hispania ","incAns1":"Italia","incAns2":"Gallia","incAns3":"Asia"},{"question":"When Christopher Columbus sailed to America, what was the first region he arrived in?","corrAns":"The Bahamas Archipelago","incAns1":"Florida","incAns2":"Isthmus of Panama","incAns3":"Nicaragua"},{"question":"Who was the leader of the Communist Party of Yugoslavia ?","corrAns":"Josip Broz Tito","incAns1":"Karadjordje Petrovic","incAns2":"Milos Obilic","incAns3":"Aleskandar Petrovic"},{"question":"In 1453, which important city fell?","corrAns":"Constantinople","incAns1":"Rome","incAns2":"Hamburg","incAns3":"Athens"},{"question":"The pantheon in Rome was used to worship what god?","corrAns":"Any god they wanted","incAns1":"Athena","incAns2":"Zeus","incAns3":"Both Athena and Zeus"},{"question":"Which famous military commander marched an army, which included war elephants, over the Alps during the Second Punic War?","corrAns":"Hannibal","incAns1":"Garmanicus","incAns2":"Alexander the Great","incAns3":"Tiberius"},{"question":"Who is the creator of the soft drink, Dr. Pepper?","corrAns":"Charles Alderton","incAns1":"James Wellington","incAns2":"Johnson Hinsin","incAns3":"Boris Heviltik"}]'
  },},
  { body: {
    quizzes: { name: 'Policits Easy Questions', user_id: 1, difficulty: 'easy', category: 'Policits' },
    questions: '[{"question":"Whose 2016 presidential campaign slogan was &quot;Make America Great Again&quot;?","corrAns":"Donald Trump","incAns1":"Ted Cruz","incAns2":"Marco Rubio","incAns3":"Bernie Sanders"},{"question":"There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.","corrAns":"True","incAns":"False"},{"question":"The largest consumer market in 2015 was...","corrAns":"The United States of America","incAns1":"Germany","incAns2":"Japan","incAns3":"United Kingdom"},{"question":"In 2016, the United Kingdom voted to stay in the EU.","corrAns":"False","incAns":"True"},{"question":"How many people are in the U.S. House of Representatives?","corrAns":"435","incAns1":"260","incAns2":"415","incAns3":"50"},{"question":"According to the United States Constitution, how old must a person be to be elected President of the United States?","corrAns":"35","incAns1":"30","incAns2":"40","incAns3":"45"},{"question":"Who was the 45th President of the United States?","corrAns":"Donald Trump","incAns1":"Barack Obama","incAns2":"Bill Clinton","incAns3":"George Bush"},{"question":"Donald Trump won the popular vote in the 2016 United States presidential election.","corrAns":"False","incAns":"True"},{"question":"Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.","corrAns":"True","incAns":"False"},{"question":"Which former US president was nicknamed &quot;Teddy&quot; after he refused to shoot a defenseless black bear?","corrAns":"Theodore Roosevelt","incAns1":"Woodrow Wilson","incAns2":"James F. Fielder","incAns3":"Andrew Jackson"}]'
  },},
  { body: {
    quizzes: { name: 'Policits Medium Questions', user_id: 1, difficulty: 'medium', category: 'Policits' },
    questions: '[{"question":"Which president erased the national debt of the United States?","corrAns":"Andrew Jackson","incAns1":"Ronald Reagan","incAns2":"John F. Kennedy","incAns3":"Franklin Roosevelt"},{"question":"Who was the only president to not be in office in Washington D.C?","corrAns":"George Washington","incAns1":"Abraham Lincoln","incAns2":"Richard Nixon","incAns3":"Thomas Jefferson"},{"question":"Due to the Nagoya Resolution, China agreed to allow Taiwan to compete separately in international sporting events under what name?","corrAns":"Chinese Taipei","incAns1":"Chinese Taiwan","incAns2":"Republic of Taiwan","incAns3":"Republic of Taipei "},{"question":"What is former United States President Bill Clinton&#039;s full name?","corrAns":"William Jefferson Clinton","incAns1":"William Roosevelt Clinton","incAns2":"William Truman Clinton","incAns3":"William Lincoln Clinton"},{"question":"Before 2016, in which other year did Donald Trump run for President?","corrAns":"2000","incAns1":"2012","incAns2":"1988","incAns3":"2008"},{"question":"Who succeeded Joseph Stalin as General Secretary of the Communist Party of the Soviet Union?","corrAns":"Nikita Khrushchev","incAns1":"Leonid Brezhnev","incAns2":"Mikhail Gorbachev","incAns3":"Boris Yeltsin"},{"question":"What was the personal nickname of the 40th Governor of the US State Louisiana, Huey Long?","corrAns":"The Kingfish","incAns1":"The Champ","incAns2":"The Hoot Owl","incAns3":"The Oracle"},{"question":"Which former US president used &quot;Let&#039;s Make America Great Again&quot; as his campaign slogan before Donald Trump&#039;s campaign?","corrAns":"Ronald Reagan","incAns1":"Jimmy Carter","incAns2":"Gerald Ford","incAns3":"Richard Nixon"},{"question":"What are the first names of the first father and son pair that were both Prime Ministers of Canada?","corrAns":"Justin and Pierre","incAns1":"John and Louis","incAns2":"Brian and Justin","incAns3":"Brian and Pierre"},{"question":"Which of the following Argentinian presidents was elected in 2015?","corrAns":"Mauricio Macri","incAns1":"Cristina Fernandez de Kirchner","incAns2":"Nestor Kirchner","incAns3":"Juan Domingo Peron"}]'
  },},
  { body: {
    quizzes: { name: 'Policits Hard Questions', user_id: 1, difficulty: 'hard', category: 'Policits' },
    questions: '[{"question":"Which Native American tribe/nation requires at least one half blood quantum (equivalent to one parent) to be eligible for membership?","corrAns":"Yomba Shoshone Tribe","incAns1":"Standing Rock Sioux Tribe","incAns2":"Kiowa Tribe of Oklahoma","incAns3":"Pawnee Nation of Oklahoma"},{"question":"Which letter do you need to have on a European driver license in order to ride any motorbikes?","corrAns":"A","incAns1":"X","incAns2":"D","incAns3":"B"},{"question":"Joko Widodo has appeared in the cover of a TIME magazine.","corrAns":"True","incAns":"False"},{"question":"&quot;Yes, America Can!&quot; was this United States politician&#039;s de facto campaign slogan in 2004.","corrAns":"George W. Bush","incAns1":"John Kerry","incAns2":"Barack Obama","incAns3":"Al Gore"},{"question":"Nazi Germany surrendered on Harry Truman&#039;s birthday while he was president.","corrAns":"True","incAns":"False"},{"question":"What is the name of Niccol&ograve; Machiavelli&#039;s work that argued effective leaders needed to crush their opponents at all costs?","corrAns":"The Prince","incAns1":"The Rape of Lucrece","incAns2":"Will to Power","incAns3":"Love&#039;s Labours Lost"},{"question":"What is centralism?","corrAns":" Concentration of power and authority in a central organization.","incAns1":"Conforming to one single common political agenda.","incAns2":"Remaining politically neutral.","incAns3":"The grey area in the spectrum of political left and right."},{"question":"George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.","corrAns":"False","incAns":"True"},{"question":"Which of these was an official candidate in the 2017 British General Election?","corrAns":"Lord Buckethead","incAns1":"James Francis","incAns2":"Robert Wimbledon","incAns3":"Sir Crumpetsby"},{"question":"Who was the longest-serving senator in US history, serving from 1959 to 2010?","corrAns":"Robert Byrd","incAns1":"Daniel Inouye","incAns2":"Strom Thurmond","incAns3":"Joe Biden"}]'
  },},
  { body: {
    quizzes: { name: 'Policits Boolean Questions', user_id: 1, difficulty: 'hard', category: 'Policits' },
    questions: '[{"question":"The S in Harry S. Truman stands for &quot;Samuel&quot;.","corrAns":"False","incAns":"True"},{"question":"There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.","corrAns":"True","incAns":"False"},{"question":"In 2016, the United Kingdom voted to stay in the EU.","corrAns":"False","incAns":"True"},{"question":"Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.","corrAns":"False","incAns":"True"},{"question":"The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.","corrAns":"False","incAns":"True"},{"question":"Joko Widodo has appeared in the cover of a TIME magazine.","corrAns":"True","incAns":"False"},{"question":"Donald Trump won the popular vote in the 2016 United States presidential election.","corrAns":"False","incAns":"True"},{"question":"George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.","corrAns":"False","incAns":"True"},{"question":"Helen Clark was the 37th Prime Minister of Australia.","corrAns":"False","incAns":"True"},{"question":"Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.","corrAns":"True","incAns":"False"}]'
  },},
  { body: {
    quizzes: { name: 'Policits Multiple Questions', user_id: 1, difficulty: 'hard', category: 'Policits' },
    questions: '[{"question":"Which of the following Pacific Islander countries is ruled by a constitutional monarchy?","corrAns":"Tonga","incAns1":"Palau","incAns2":"Fiji","incAns3":"Kiribati"},{"question":"Which Native American tribe/nation requires at least one half blood quantum (equivalent to one parent) to be eligible for membership?","corrAns":"Yomba Shoshone Tribe","incAns1":"Standing Rock Sioux Tribe","incAns2":"Kiowa Tribe of Oklahoma","incAns3":"Pawnee Nation of Oklahoma"},{"question":"Due to the Nagoya Resolution, China agreed to allow Taiwan to compete separately in international sporting events under what name?","corrAns":"Chinese Taipei","incAns1":"Chinese Taiwan","incAns2":"Republic of Taiwan","incAns3":"Republic of Taipei "},{"question":"Which of the following United States senators is known for performing a 24-hour long filibuster?","corrAns":"Strom Thurmond","incAns1":"Roy Blunt","incAns2":"John Barrasso","incAns3":"Chuck Schumer"},{"question":"In United States history, how many vice presidents did Franklin D. Roosevelt have during his time in office as president?","corrAns":"3","incAns1":"1","incAns2":"2","incAns3":"0"},{"question":"Former United States President Bill Clinton famously played which instrument?","corrAns":"Saxophone","incAns1":"Baritone horn","incAns2":"Piano","incAns3":"Violin"},{"question":"Who succeeded Joseph Stalin as General Secretary of the Communist Party of the Soviet Union?","corrAns":"Nikita Khrushchev","incAns1":"Leonid Brezhnev","incAns2":"Mikhail Gorbachev","incAns3":"Boris Yeltsin"},{"question":"In June 2017, Saudi Arabia and Egypt broke off ties with which country over its supposed support for terrorism?","corrAns":"Qatar","incAns1":"Bahrain","incAns2":"United States of America","incAns3":"Russia"},{"question":"Who was the longest-serving senator in US history, serving from 1959 to 2010?","corrAns":"Robert Byrd","incAns1":"Daniel Inouye","incAns2":"Strom Thurmond","incAns3":"Joe Biden"},{"question":"The Watergate Scandal occured in what year?","corrAns":"1972","incAns1":"1973","incAns2":"1974","incAns3":"1971"}]'
  },},
  { body: {
    quizzes: { name: 'Sports Easy Questions', user_id: 1, difficulty: 'easy', category: 'Sports' },
    questions: '[{"question":"Which of the following sports is not part of the triathlon?","corrAns":"Horse-Riding","incAns1":"Cycling","incAns2":"Swimming","incAns3":"Running"},{"question":"In golf, what name is given to a hole score of two under par?","corrAns":"Eagle","incAns1":"Birdie","incAns2":"Bogey","incAns3":"Albatross"},{"question":"Which team has won the most Stanley Cups in the NHL?","corrAns":"Montreal Canadians","incAns1":"Chicago Blackhawks","incAns2":"Toronto Maple Leafs","incAns3":"Detroit Red Wings"},{"question":"What is the most common type of pitch thrown by pitchers in baseball?","corrAns":"Fastball","incAns1":"Slowball","incAns2":"Screwball","incAns3":"Palmball"},{"question":"Who is often called &quot;the Maestro&quot; in the men&#039;s tennis circuit?","corrAns":"Roger Federer","incAns1":"Bill Tilden","incAns2":"Boris Becker","incAns3":"Pete Sampras"},{"question":"Who won the premier league title in the 2015-2016 season following a fairy tale run?","corrAns":"Leicester City","incAns1":"Tottenham Hotspur","incAns2":"Watford","incAns3":"Stoke City"},{"question":"When was the FC Schalke 04 founded?","corrAns":"1904","incAns1":"1909","incAns2":"2008","incAns3":"1999"},{"question":"&quot;Stadium of Light&quot; is the home stadium for which soccer team?","corrAns":"Sunderland FC","incAns1":"Barcelona FC","incAns2":"Paris Saints-Germain","incAns3":"Manchester United"},{"question":"Which country will host the 2022 FIFA World Cup?","corrAns":"Qatar","incAns1":"USA","incAns2":"Japan","incAns3":"Switzerland"},{"question":"Who won the UEFA Champions League in 2017?","corrAns":"Real Madrid C.F.","incAns1":"Atletico Madrid","incAns2":"AS Monaco FC","incAns3":"Juventus F.C."}]'
  },},
  { body: {
    quizzes: { name: 'Sports Medium Questions', user_id: 1, difficulty: 'medium', category: 'Sports' },
    questions: '[{"question":"With which team did Michael Schumacher make his Formula One debut at the 1991 Belgian Grand Prix?","corrAns":"Jordan","incAns1":"Benetton","incAns2":"Ferrari","incAns3":"Mercedes"},{"question":"Which of these teams isn&#039;t a member of the NHL&#039;s &quot;Original Six&quot; era?","corrAns":"Philadelphia Flyers","incAns1":"New York Rangers","incAns2":"Toronto Maple Leafs","incAns3":"Boston Bruins"},{"question":"Who was the British professional wrestler Shirley Crabtree better known as?","corrAns":"Big Daddy","incAns1":"Giant Haystacks","incAns2":"Kendo Nagasaki","incAns3":"Masambula"},{"question":"Which Formula One driver was nicknamed &#039;The Professor&#039;?","corrAns":"Alain Prost","incAns1":"Ayrton Senna","incAns2":"Niki Lauda","incAns3":"Emerson Fittipaldi"},{"question":"Which country is hosting the 2022 FIFA World Cup?","corrAns":"Qatar","incAns1":"Uganda","incAns2":"Vietnam","incAns3":"Bolivia"},{"question":"What is the oldest team in Major League Baseball?","corrAns":"Atlanta Braves","incAns1":"Chicago Cubs","incAns2":"Cincinnati Reds","incAns3":"St. Louis Cardinals"},{"question":"What is the exact length of one non-curved part in Lane 1 of an Olympic Track?","corrAns":"84.39m","incAns1":"100m","incAns2":"100yd","incAns3":"109.36yd"},{"question":"Which of the following pitchers was named National League Rookie of the Year for the 2013 season?","corrAns":"Jose Fernandez","incAns1":"Jacob deGrom","incAns2":"Shelby Miller","incAns3":"Matt Harvey"},{"question":"Who won the 2011 Stanley Cup?","corrAns":"Boston Bruins","incAns1":"Montreal Canadiens","incAns2":"New York Rangers","incAns3":"Toronto Maple Leafs"},{"question":"What country hosted the 2014 Winter Olympics?","corrAns":"Russia","incAns1":"Canada","incAns2":"United States","incAns3":"Germany"}]'
  },},
  { body: {
    quizzes: { name: 'Sports Hard Questions', user_id: 1, difficulty: 'hard', category: 'Sports' },
    questions: '[{"question":"Where was the Games of the XXII Olympiad held?","corrAns":"Moscow","incAns1":"Barcelona","incAns2":"Tokyo","incAns3":"Los Angeles"},{"question":"Which female player won the gold medal of table tennis singles in 2016 Olympics Games?","corrAns":"DING Ning (China)","incAns1":"LI Xiaoxia (China)","incAns2":"Ai FUKUHARA (Japan)","incAns3":"Song KIM (North Korea)"},{"question":"What is the full name of the footballer &quot;Cristiano Ronaldo&quot;?","corrAns":"Cristiano Ronaldo dos Santos Aveiro","incAns1":"Cristiano Ronaldo los Santos Diego","incAns2":"Cristiano Armando Diego Ronaldo","incAns3":"Cristiano Luis Armando Ronaldo"},{"question":"What team did England beat in the semi-final stage to win in the 1966 World Cup final?","corrAns":"Portugal","incAns1":"West Germany","incAns2":"Soviet Union","incAns3":"Brazil"},{"question":"The Mazda 787B won the 24 Hours of Le Mans in what year?","corrAns":"1991","incAns1":"1990","incAns2":"2000","incAns3":"1987"},{"question":"What is &ldquo;The Sport of Kings&rdquo;?","corrAns":"Horse Racing","incAns1":"Chess","incAns2":"Jousting","incAns3":"Fencing"},{"question":"Which of these Russian cities did NOT contain a stadium that was used in the 2018 FIFA World Cup?","corrAns":"Vladivostok","incAns1":"Rostov-on-Don","incAns2":"Yekaterinburg","incAns3":"Kaliningrad"},{"question":"In Canadian football, scoring a rouge is worth how many points?","corrAns":"1","incAns1":"2","incAns2":"3","incAns3":"4"},{"question":"The AHL affiliate team of the Boston Bruins is named what?","corrAns":"Providence Bruins","incAns1":"New Haven Bruins","incAns2":"Cambridge Bruins","incAns3":"Hartford Bruins"},{"question":"Which English football team is nicknamed &#039;The Tigers&#039;?","corrAns":"Hull City","incAns1":"Cardiff City","incAns2":"Bristol City","incAns3":"Manchester City"}]'
  },},
  { body: {
    quizzes: { name: 'Sports Boolean Questions', user_id: 1,  difficulty: 'hard', category: 'Sports' },
    questions: '[{"question":"Skateboarding will be included in the 2020 Summer Olympics in Tokyo.","corrAns":"True","incAns":"False"},{"question":"Tennis was once known as Racquetball.","corrAns":"False","incAns":"True"},{"question":"The Olympics tennis court is a giant green screen.","corrAns":"True","incAns":"False"},{"question":"Formula E is an auto racing series that uses hybrid electric race cars.","corrAns":"False","incAns":"True"},{"question":"In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.","corrAns":"False","incAns":"True"},{"question":"Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.","corrAns":"True","incAns":"False"},{"question":"During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.","corrAns":"True","incAns":"False"},{"question":"In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.","corrAns":"True","incAns":"False"},{"question":"ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.","corrAns":"True","incAns":"False"},{"question":"There are a total of 20 races in Formula One 2016 season.","corrAns":"False","incAns":"True"}]'
  },},
  { body: {
    quizzes: { name: 'Sports Multiple Questions', user_id: 1, difficulty: 'hard', category: 'Sports' },
    questions: '[{"question":"Who was the British professional wrestler Shirley Crabtree better known as?","corrAns":"Big Daddy","incAns1":"Giant Haystacks","incAns2":"Kendo Nagasaki","incAns3":"Masambula"},{"question":"Which team won the 2015-16 English Premier League?","corrAns":"Leicester City","incAns1":"Liverpool","incAns2":"Cheslea","incAns3":"Manchester United"},{"question":"What is the exact length of one non-curved part in Lane 1 of an Olympic Track?","corrAns":"84.39m","incAns1":"100m","incAns2":"100yd","incAns3":"109.36yd"},{"question":"Who won the 2015 College Football Playoff (CFP) National Championship? ","corrAns":"Ohio State Buckeyes","incAns1":"Alabama Crimson Tide","incAns2":"Clemson Tigers","incAns3":"Wisconsin Badgers"},{"question":"When was the first official international game played?","corrAns":"1872","incAns1":"1880","incAns2":"1863","incAns3":"1865"},{"question":"In what sport does Fanny Chmelar compete for Germany?","corrAns":"Skiing","incAns1":"Swimming","incAns2":"Showjumping","incAns3":"Gymnastics"},{"question":"Who did Steven Gerrard win the Champions League with?","corrAns":"Liverpool","incAns1":"Real Madrid","incAns2":"Chelsea","incAns3":"Man City"},{"question":"Which year did Jenson Button won his first ever Formula One World Drivers&#039; Championship?","corrAns":"2009","incAns1":"2010","incAns2":"2007","incAns3":"2006"},{"question":"Which country will host the 2022 FIFA World Cup?","corrAns":"Qatar","incAns1":"USA","incAns2":"Japan","incAns3":"Switzerland"},{"question":"What is Tiger Woods&#039; all-time best career golf-score?","corrAns":"61","incAns1":"65","incAns2":"63","incAns3":"67"}]'
  },},
]
