name: Quiz Whiz Deploy Server

on:
  pull_request:
    branches:
      - main
      - cd-test
    types: [closed]

jobs:
  build:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quizwhiz-server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_KEY  }}
          script: |
            echo "${{ secrets.SERVER_ENV_FILE }}" > /home/ubuntu/quiz-whiz/server/.env
            docker login
            docker stop quizwhiz-server
            docker rm quizwhiz-server
            docker rmi -f $(docker images -aq)
            docker builder prune -a -f
            docker pull gbmytabc/quizwhiz-server:latest
            docker run -d --name quizwhiz-server -p 8080:8080 gbmytabc/quizwhiz-server:latest
  